if GetLocale() == "deDE" then
DBM_SUNWELL						= "Sonnenbrunnenplateau"

-- Kalecgos
DBM_KAL_NAME					= "Kalecgos"
DBM_KAL_DESCRIPTION 			= "Zeigt Timer und Warnungen für Kalecgos an."

DBM_KAL_KILL_NAME				= "Sathrovarr der Verderber"

DBM_KAL_OPTION_BREATH			= "Frostatem ansagen"
DBM_KAL_OPTION_PREBREATH		= "\"Frostatem bald\" Warnung anzeigen"
DBM_KAL_OPTION_WM_WARN			= "Wilde Magie ansagen"
DBM_KAL_OPTION_WM_WHISPER		= "Whisper an Wilde Magie-Ziele schicken"
DBM_KAL_OPTION_COA_WARN			= "Fluch der unermesslichen Pein ansagen"
DBM_KAL_OPTION_PORT_PREWARN		= "\"Portal bald\" Warnung anzeigen"
DBM_KAL_OPTION_PORT_WARN		= "Portale ansagen"
DBM_KAL_OPTION_WM_WARN2			= "Wilde Magie Typ anzeigen"
DBM_KAL_OPTION_SHOWFRAME		= "Spektralreich-Frame anzeigen"
DBM_KAL_FRAME_UPWARDS			= "Spektralreich-Frame nach oben aufbauen"
DBM_KAL_FRAME_UPWARDS2			= "Nach oben aufbauen"
DBM_KAL_FRAME_COLORS			= "Klassenfarben verwenden"
DBM_KAL_OPTION_RANGE			= "Rangecheck-Frame anzeigen"
DBM_KAL_OPTION_STRIKE			= "Stoß der Verderbnis ansagen"
DBM_KAL_OPTION_COA_ICON			= "Icon auf Fluch der Pein Ziele setzen"

DBM_KAL_SPELLID_BREATH			= 44799
DBM_KAL_SPELLIDS_WM				= { -- DO NOT TRANSLATE
	[44978] = "Heal",	-- Healing done by spells and effects increased by 100%.
	[45001] = "Cast",	-- Casting time increased by 100%.
	[45002] = "Hit",	-- Chance to hit with melee and ranged attacks reduced by 50%.
	[45004] = "Crit",	-- Damage done by critical hits increased by 100%.
	[45006] = "Aggro",	-- Increases threat generated by 100%.
	[45010] = "Cost"	-- Spell and ability costs reduced by 50%.
}
DBM_KAL_SPELLID_COA1			= 45032
DBM_KAL_SPELLID_COA2			= 45034
DBM_KAL_SPELLID_PORT1			= 46021
DBM_KAL_SPELLID_BLAST			= 44866
DBM_KAL_SPELLID_BUFFET			= 45018
DBM_KAL_YELL_PULL				= "Ah ha haa!! Nicht länger werde ich Malygos' Sklave sein! Fordert mich heraus und Ihr werdet vernichtet!"

DBM_KAL_WARN_BREATH				= "Frostatem"
DBM_KAL_WARN_BREATH_SOON		= "Frostatem bald"
DBM_KAL_WHISPER_WM				= "Wilde Magie: %s"
DBM_KAL_WARN_COA				= "Fluch der Pein: >%s<"
DBM_KAL_WARN_PORT				= "Portal #%d: >%s< (Gruppe %d)"
DBM_KAL_WARN_PORT_SOON			= "Portal #%d bald"
DBM_KAL_WARN_STRIKE				= "Stoß der Verderbnis auf >%s<"

DBM_KAL_WARN_CASTTIME			= "+100% Castzeit"
DBM_KAL_WARN_HIT				= "-50% Hit-Chance"
DBM_KAL_WARN_CRIT				= "+100% Crit-Schaden"
DBM_KAL_WARN_AGGRO				= "+100% Bedrohung"
DBM_KAL_WARN_COST				= "-50% Zauberkosten"
DBM_KAL_WARN_HEAL				= "+100% Heilung"

DBM_KAL_FRAME_TITLE				= "Spektralreich"
DBM_KAL_MENU_LOCK				= "Frame sperren"
DBM_KAL_FRAME_HIDE				= "Frame verstecken"

DBM_SBT["Arcane Buffet"]		= "Arkanpuffer";
DBM_SBT["Frost Breath"]			= "Frostatem";
DBM_SBT["Ported"]				= "Teleportiert";
DBM_SBT["Exhausted"]			= "Erschöpft";
DBM_SBT["Kal"] = {
	{"CoA: (.*)", "Fluch: %1"},
	{"Next Portal #(.*)", "Nächstes Portal #%1"},
	{"Portal #(.*)", "Portal #%1"},	
}

-- Brutallus 
DBM_BRUTALLUS_NAME				= "Brutallus" 
DBM_BRUTALLUS_DESCRIPTION		= "Zeigt Timer und Warnungen für Brutallus." 

DBM_BRUTALLUS_YELL_PULL			= "Ah, mehr Lämmer zum Schlachten!"

DBM_BRUTALLUS_OPTION_BURN		= "Brand ansagen"
DBM_BRUTALLUS_OPTION_BURN2		= "Gesprungenen Brand ansagen"
DBM_BRUTALLUS_OPTION_BAR_BURN2	= "Gesprungener Brand: <ziel>"
DBM_BRUTALLUS_OPTION_METEOR		= "Meteor ansagen"
DBM_BRUTALLUS_OPTION_STOMP		= "Stampfen ansagen"
DBM_BRUTALLUS_OPTION_BURN3		= "Icon auf Brand-Ziel setzen"
DBM_BRUTALLUS_OPTION_BURN4		= "Special Warning anzeigen, wenn du Brand hast"
DBM_BRUTALLUS_OPTION_DEL_BURN	= "Verwende verzögerten Brand Timer"
DBM_BRUTALLUS_OPTION_DEL_BURN2	= "Verwende verzögerte Brand Warnung"
DBM_BRUTALLUS_OPTION_PRESTOMP	= "5 Sekunden Warnung für Stampfen anzeigen"

DBM_BRUTALLUS_WARN_BURN			= "Brand: >%s<"
DBM_BRUTALLUS_WHISP_BURN		= "Brand auf dir!"
DBM_BRUTALLUS_WARN_STOMP		= "Stampfen: >%s<"
DBM_BRUTALLUS_WARN_METEOR		= "Meteor"
DBM_BRUTALLUS_WARN_DEL_BURN		= "15 Sek Brand auf >%s<"
DBM_BRUTALLUS_WARN_STOMP_SOON	= "Stampfen in 5 Sek"

DBM_SBT["Next Burn"]	= "Nächster Brand";
DBM_SBT["Next Meteor"]	= "Nächster Meteor";
DBM_SBT["Next Stomp"]	= "Nächstes Stampfen";
DBM_SBT["Brutallus"] = {
	{"Burn: (.*)", "Brand: %1"},
	{"Jumped Burn: (.*)", "Brand: %1"},
}


-- Felmyst
DBM_FELMYST_NAME				= "Teufelsruch"
DBM_FELMYST_DESCRIPTION			= "Zeigt Timer für die Phasen an und zeigt Warnungen für Gasnova, Einschließen und Tiefer Atem."

DBM_FELMYST_OPTION_SPECGAS		= "Special warning für Gasnova anzeigen"
DBM_FELMYST_OPTION_GASSOON		= "\"Gasnova bald\" Warnung anzeigen"
DBM_FELMYST_OPTION_BREATH_SOON	= "\"Tiefer Atem bald\" Warnung anzeigen"
DBM_FELMYST_OPTION_VAPOR		= "Ziel von Dämonischer Dampf ansagen"

DBM_FELMYST_EMOTE_BREATH		= "%s holt tief Luft."

DBM_FELMYST_WARN_GAS			= "Gasnova"
DBM_FELMYST_WARN_GAS_SOON		= "Gasnova bald"
DBM_FELMYST_WARN_ENCAPS			= "Einschließen: >%s<"
DBM_FELMYST_WARN_AIR			= "Teufelsruch hebt ab"
DBM_FELMYST_LAND_SOON			= "Teufelsruch landet in 10 Sek"
DBM_FELMYST_BREATH_SOON_FMT		= "Tiefer Atem #%d in 10 Sek"
DBM_FELMYST_BREATH_SOON5_FMT	= "Tiefer Atem #%d in 5 Sek"
DBM_FELMYST_BREATH_NOW_FMT		= "Tiefer Atem #%d"
DBM_FELMYST_ENCAPS_WARN_SAY		= "Einschließen auf mir! Lauft weg!"
DBM_FELMYST_WARN_VAPOR			= "Dämonischer Dampf: >%s<"

DBM_SBT["Air Phase"]			= "Abheben"
DBM_SBT["Next Gas Nova"]		= "Nächste Gasnova"
DBM_SBT["Gas Nova"]				= "Gasnova"
DBM_SBT["Ground Phase"]			= "Landung"
DBM_SBT["Next Deep Breath"]		= "Nächster tiefer Atem"
DBM_SBT["Deep Breath"]			= "Tiefer Atem"


-- Eredar Twins
DBM_TWINS_NAME					= "Eredar Zwillinge"
DBM_TWINS_DESCRIPTION			= "Zeigt Timer für Schattenklingen, Schattennova, Großbrand und Pyrogen."
DBM_TWINS_OPTION_BLADES			= "Schattenklingen ansagen"
DBM_TWINS_OPTION_BUFF			= "Pyrogen ansagen"
DBM_TWINS_OPTION_BLOW			= "Verwirrender Schlag ansagen"
DBM_TWINS_OPTION_BLOW_SOON		= "\"Verwirrender Schlag bald\" Warnung anzeigen"
DBM_TWINS_OPTION_CONFLAG		= "Großbrand: Ansagen"
DBM_TWINS_OPTION_CONFLAG2		= "Großbrand: Flüstern"
DBM_TWINS_OPTION_CONFLAG3		= "Großbrand: Special Warnung"
DBM_TWINS_OPTION_CONFLAG4		= "Großbrand: Icon"
DBM_TWINS_OPTION_NOVA			= "Schattennova: Ansagen"
DBM_TWINS_OPTION_NOVA2			= "Schattennova: Flüstern"
DBM_TWINS_OPTION_NOVA3			= "Schattennova: Special Warnung"
DBM_TWINS_OPTION_NOVA4			= "Schattennova: Icon"

DBM_TWINS_MOB_WL				= "Großhexenmeisterin Alythess"
DBM_TWINS_MOB_SOCR				= "Lady Sacrolash"
DBM_TWINS_EMOTE_CONFLAG			= "Alythess zielt mit Großbrand auf (.+)%."
DBM_TWINS_EMOTE_NOVA			= "Sacrolash zielt mit Schattennova auf (.+)%."

DBM_TWINS_WARN_BLADES			= "Schattenklingen"
DBM_TWINS_WARN_NOVA_ON			= "Schattennova: >%s<"
DBM_TWINS_WARN_BUFF				= "Pyrogen"
DBM_TWINS_WARN_CONFLAG_ON		= "Großbrand: >%s<"
DBM_TWINS_WARN_BLOW_SOON		= "Verwirrender Schlag bald"
DBM_TWINS_WARN_BLOW				= "Verwirrender Schlag"
DBM_TWINS_WHISPER_CONFLAG		= "Großbrand auf dir!"
DBM_TWINS_WHISPER_NOVA			= "Schattennova auf dir!"

DBM_SBT["Next Shadow Blades"]	= "Nächste Schattenklingen"
DBM_SBT["Shadow Blades"]		= "Schattenklingen"
DBM_SBT["Next Confounding Blow"]= "Nächster Verwirrender Schlag"
DBM_SBT["Next Shadow Nova"]		= "Nächste Schattennova"
DBM_SBT["Shadow Nova"]			= "Schattennova"



-- M'uru
DBM_MURU_NAME					= "M'uru"
DBM_MURU_DESCRIPTION			= "Sagt Dunkelheit, Finstere Scheusale, Leerenwandler, Humanoide und Schwarzes Loch an."
DBM_MURU_OPTION_VOID			= "Leerenwandler ansagen"
DBM_MURU_OPTION_VOID_SOON		= "5 Sekunden Warnung für Leerenwandler anzeigen"
DBM_MURU_OPTION_HUM				= "Humanoide ansagen"
DBM_MURU_OPTION_HUM_SOON		= "5 Sekunden Warnung für Humanoide anzeigen"
DBM_MURU_OPTION_DARKNESS		= "Dunkelheit und Scheusale in Phase 1 ansagen"
DBM_MURU_OPTION_DARKNESS_SOON	= "\"Dunkelheit/Scheusale bald\" Warnung anzeigen"
DBM_MURU_OPTION_HOLE_WARN		= "Schwarzes Loch ansagen"
DBM_MURU_OPTION_HOLE_SOON_WARN	= "\"Schwarzes Loch bald\" Warnung anzeigen"
DBM_MURU_OPTION_WARN_FIEND		= "Scheusale in Phase 2 ansagen"

DBM_MURU_ENTROPIUS				= "Entropius"

DBM_MURU_DARKNESS_SOON			= "Dunkelheit und Finstere Scheusale in 5 Sek"
DBM_MURU_DARKNESS_INC			= "Dunkelheit und Finstere Scheusale"
DBM_MURU_WARN_VOID_SOON			= "Leerenwandler in 5 Sek"
DBM_MURU_WARN_VOID_NOW			= "Leerenwandler"
DBM_MURU_WARN_HUMANOIDS_SOON	= "Humanoide in 5 Sek"
DBM_MURU_WARN_HUMANOIDS_NOW		= "Humanoide"
DBM_MURU_WARN_FIEND				= "Finsteres Scheusal"
DBM_MURU_WARN_BLACKHOLE			= "Schwarzes Loch"
DBM_MURU_WARN_BLACKHOLE_SOON	= "Schwarzes Loch bald"
DBM_MURU_WARN_P2				= "Phase 2"

DBM_SBT["Humanoids"]			= "Humanoide"
DBM_SBT["Void Sentinel"]		= "Leerenwandler"
DBM_SBT["Next Darkness"]		= "Nächste Dunkelheit"
DBM_SBT["Next Black Hole"]		= "Nächstes schwarzes Loch"


DBM_KIL_YELL_PULL				= "Die Entbehrlichen sind dahin - so sei es! Jetzt werde ich dort erfolgreich sein, wo Sargeras versagt hat! Ich werde diese jämmerliche Welt ausbluten lassen und meinen Platz als wahrer Meister der Brennenden Legion einnehmen! Das Ende ist gekommen! Lasst uns diese Welt dem Erdboden gleichmachen!"
-- Kil'jaeden
DBM_KIL_NAME					= "Kil'jaeden"
DBM_KIL_DESCRIPTION				= "Announces Orbs, Darkness, Shield, Reflections and Fire Bloom"

DBM_KIL_OPTION_RANGE			= "Show range check"
DBM_KIL_OPTION_SHIELD			= "Announce Shield of the Blue"
DBM_KIL_OPTION_ORB				= "Announce Orbs"
DBM_KIL_OPTION_FIRETARGET		= "Announce Fire Bloom targets"
DBM_KIL_OPTION_FIRESAY			= "Send chat message when you are afflicted by Fire Bloom"
DBM_KIL_OPTION_FIREWHISP		= "Send whisper to Fire Bloom targets"
DBM_KIL_OPTION_FIREICON			= "Set icons on Fire Bloom targets"
DBM_KIL_OPTION_SHOWFRAME		= "Show Fire Bloom target list"
DBM_KIL_OPTION_WARNREFL			= "Announce Sinister Reflections"
DBM_KIL_OPTION_DARTS			= "Announce Flame Darts"
DBM_KIL_OPTION_DRAGONORB		= "Announce Dragon Orbs"

DBM_KIL_YELL_PULL				= "Die Entbehrlichen sind dahin - so sei es! Jetzt werde ich dort erfolgreich sein, wo Sargeras versagt hat! Ich werde diese jämmerliche Welt ausbluten lassen und meinen Platz als wahrer Meister der Brennenden Legion einnehmen! Das Ende ist gekommen! Lasst uns diese Welt dem Erdboden gleichmachen!"
DBM_KIL_YELL_PHASE2_1			= "The enemy is among you!" -- this actually announces Sinister Reflections and not phase 2
DBM_KIL_YELL_PHASE2_2			= "Who can you trust!"

DBM_KIL_WARN_PHASE1				= "Phase 2"
DBM_KIL_WARN_PHASE2				= "Phase 3"
DBM_KIL_WARN_PHASE3				= "Phase 4 - Meteors"
DBM_KIL_WARN_PHASE4				= "Phase 5 - Enrage"
DBM_KIL_WARN_SHIELD				= "Shield of the Blue"
DBM_KIL_WARN_DARKNESS			= "Darkness"
DBM_KIL_WARN_DARKNESS_SOON		= "Darkness soon"
DBM_KIL_WARN_ORB				= "Orb spawned"
DBM_KIL_WARN_ORBS				= "Orbs spawned"
--DBM_KIL_WARN_FIRE				= "Fire Bloom incoming"
DBM_KIL_WARN_FIRE_ON			= "Fire Bloom: >%s<"
DBM_KIL_WARN_DARKNESS_NOW		= "Darkness of a Thousand Souls"
DBM_KIL_WARN_REFLECTIONS		= "Sinister Reflections"
DBM_KIL_WARN_FIRE_SAY			= "Fire Bloom on me!"
DBM_KIL_WARN_FIRE_WHISPER		= "Fire Bloom on you!"
DBM_KIL_WARN_DARTS_SOON			= "Flame Darts in 5 sec"
DBM_KIL_WARN_DARTS				= "Flame Darts"
DBM_KIL_WARN_DRAGORB_SOON		= "Dragon Orb in 5 sec"
DBM_KIL_WARN_DRAGORB_NOW		= "Dragon Orb spawned"


DBM_KIL_FRAME_TITLE				= "Fire Bloom"
DBM_KIL_MENU_LOCK				= DBM_KAL_MENU_LOCK
DBM_KIL_FRAME_COLORS			= DBM_KAL_FRAME_COLORS
DBM_KIL_FRAME_UPWARDS			= "Expand Fire Bloom target list upwards"
DBM_KIL_FRAME_UPWARDS2			= DBM_KAL_FRAME_UPWARDS2
DBM_KIL_FRAME_HIDE				= DBM_KAL_FRAME_HIDE
end
