-- ------------------------------------------- --
--   Deadly Boss Mods - Chinese localization   --
--    by Diablohu<白银之手> @ 二区-轻风之语    --
--              www.dreamgen.cn                --
--                    7/6/2008                 --
-- ------------------------------------------- --

if (GetLocale() == "zhCN") then

DBM_SW_TAB						= "SunwellTab"
DBM_SUNWELL						= "太阳之井高地"


-- Kalecgos
	DBM_KAL_NAME					= "卡雷苟斯"
	DBM_KAL_DESCRIPTION 			= "警报冰霜吐息, 狂野魔法和无边苦痛诅咒"

	DBM_KAL_KILL_NAME				= "腐蚀者萨索瓦尔"
	DBM_KAL_DEMON_SHORT				= "萨索瓦尔"

	DBM_KAL_OPTION_BREATH			= "警报冰霜吐息"
	DBM_KAL_OPTION_PREBREATH		= "显示“冰霜吐息 - 即将施放”警报"
	DBM_KAL_OPTION_WM_WARN			= "警报狂野魔法"
	DBM_KAL_OPTION_WM_WHISPER		= "对狂野魔法的目标发送密语"
	DBM_KAL_OPTION_COA_WARN			= "警报无边苦痛诅咒"
	DBM_KAL_OPTION_COA_ICON			= "对无边苦痛诅咒的目标添加标记"
	DBM_KAL_OPTION_PORT_PREWARN		= "显示“传送 - 即将施放”警报"
	DBM_KAL_OPTION_PORT_WARN		= "警报传送"
	DBM_KAL_OPTION_WM_WARN2			= "显示狂野魔法类型"
	DBM_KAL_OPTION_SHOWFRAME		= "显示灵魂世界框体"
	DBM_KAL_FRAME_UPWARDS			= "灵魂世界框体向上延伸"
	DBM_KAL_FRAME_UPWARDS2			= "灵魂世界框体向上延伸"
	DBM_KAL_FRAME_COLORS			= "使用职业颜色"
	DBM_KAL_OPTION_RANGE			= "显示距离框体"
	DBM_KAL_OPTION_STRIKE			= "警报腐蚀打击"
	DBM_KAL_OPTION_FRAME			= "显示首领生命值框体"

	DBM_KAL_SPELLID_BREATH			= 44799
	DBM_KAL_SPELLIDS_WM				= {
		[44978] = "治疗",	-- Healing done by spells and effects increased by 100%.
		[45001] = "施法",	-- Casting time increased by 100%.
		[45002] = "命中",	-- Chance to hit with melee and ranged attacks reduced by 50%.
		[45004] = "爆击",	-- Damage done by critical hits increased by 100%.
		[45006] = "威胁",	-- Increases threat generated by 100%.
		[45010] = "消耗"	-- Spell and ability costs reduced by 50%.
	}
	DBM_KAL_SPELLID_COA1			= 45032
	DBM_KAL_SPELLID_COA2			= 45034
	DBM_KAL_SPELLID_PORT1			= 46021
	DBM_KAL_SPELLID_BLAST			= 44866
	DBM_KAL_SPELLID_BUFFET			= 45018
	DBM_KAL_YELL_PULL				= "啊！我不再是玛利苟斯的奴隶了！所有挑战我的人都要被消灭！"

	DBM_KAL_WARN_BREATH				= "冰霜吐息"
	DBM_KAL_WARN_BREATH_SOON		= "冰霜吐息 - 即将施放"
	DBM_KAL_WHISPER_WM				= "狂野魔法 -> %s"
	DBM_KAL_WARN_COA				= "无边苦痛诅咒 -> >%s<"
	DBM_KAL_WARN_PORT				= "传送 #%d -> >%s< (%d组)"
	DBM_KAL_WARN_PORT_SOON			= "传送 #%d - 即将施放"
	DBM_KAL_WARN_STRIKE				= "腐蚀打击 -> >%s<"

	DBM_KAL_WARN_CASTTIME			= "+100%施法时间"
	DBM_KAL_WARN_HIT				= "-50%命中几率"
	DBM_KAL_WARN_CRIT				= "+100%爆击伤害"
	DBM_KAL_WARN_AGGRO				= "+100%威胁值"
	DBM_KAL_WARN_COST				= "-50%技能消耗"
	DBM_KAL_WARN_HEAL				= "+100%治疗效果"

	DBM_KAL_FRAME_TITLE				= "灵魂世界"
	DBM_KAL_MENU_LOCK				= "锁定框体"
	DBM_KAL_FRAME_HIDE				= "隐藏框体"
	
	DBM_KAL_HEALTHFRAME_TITLE		= "首领生命值"

	DBM_SBT["Arcane Buffet"]		= "奥术打击";
	DBM_SBT["Frost Breath"]			= "冰霜吐息";
	DBM_SBT["Next Portal"]			= "下一次传送";
	DBM_SBT["Portal"]				= "传送";
	DBM_SBT["Ported"]				= "被传送";
	DBM_SBT["Exhausted"]			= "虚弱 - 无法被传送";
	DBM_SBT["Kal"] = {
		  [1] = {"CoA: (.*)", "无边苦痛诅咒 -> %1"},
		  [2] = {"Next Portal #(.*)", "下一次传送 #%1"},
		  [3] = {"Portal #(.*)", "传送 #%1"},	
	}
	DBM_SBT["卡雷苟斯"] = DBM_SBT["Kal"]


-- Brutallus 
	DBM_BRUTALLUS_NAME				= "布鲁塔卢斯" 
	DBM_BRUTALLUS_DESCRIPTION		= "警报燃烧和激怒" 
	
	DBM_BRUTALLUS_YELL_PULL			= "啊，又来了一群小绵羊！"

	DBM_BRUTALLUS_OPTION_BURN		= "警报燃烧"
	DBM_BRUTALLUS_OPTION_BURN2		= "警报燃烧蔓延"
	DBM_BRUTALLUS_OPTION_BAR_BURN2	= "燃烧蔓延 -> <目标>"
	DBM_BRUTALLUS_OPTION_METEOR		= "警报流星猛击"
	DBM_BRUTALLUS_OPTION_STOMP		= "警报践踏"
	DBM_BRUTALLUS_OPTION_BURN3		= "对燃烧的目标添加标记"
	DBM_BRUTALLUS_OPTION_BURN4		= "当你成为燃烧目标时显示特殊警报"
	DBM_BRUTALLUS_OPTION_DEL_BURN	= "显示燃烧效果计时"
	DBM_BRUTALLUS_OPTION_DEL_BURN2	= "警报燃烧效果剩余时间"
	DBM_BRUTALLUS_OPTION_PRESTOMP	= "显示“践踏 - 5秒后施放”警报"

	DBM_BRUTALLUS_WARN_BURN			= "燃烧 -> >%s<"
	DBM_BRUTALLUS_WHISP_BURN		= "你正在燃烧！"
	DBM_BRUTALLUS_WARN_STOMP		= "践踏 -> >%s<"
	DBM_BRUTALLUS_WARN_METEOR		= "流星猛击"
	DBM_BRUTALLUS_WARN_DEL_BURN		= ">%s<的燃烧还有15秒"
	DBM_BRUTALLUS_WARN_STOMP_SOON	= "践踏 - 5秒后施放"

	DBM_SBT["Enrage"]		= "激怒";
	DBM_SBT["Next Burn"]	= "下一次燃烧";
	DBM_SBT["Next Meteor"]	= "下一次流星猛击";
	DBM_SBT["Next Stomp"]	= "下一次践踏";
	DBM_SBT["Brutallus"] = {
		  [1] = {"Burn: (.*)", "燃烧 -> %1"},
		  [2] = {"Jumped Burn: (.*)", "燃烧蔓延 -> %1"},
	}
	DBM_SBT["布鲁塔卢斯"] = DBM_SBT["Brutallus"]


-- Felmyst
	DBM_FELMYST_NAME				= "菲米丝"
	DBM_FELMYST_DESCRIPTION			= "警报毒气新星, 深呼吸和恶魔蒸汽"

	DBM_FELMYST_OPTION_SPECGAS		= "对毒气新星技能显示特殊警报"
	DBM_FELMYST_OPTION_GASSOON		= "显示“毒气新星 - 即将施放”警报（不精确）"
	DBM_FELMYST_OPTION_BREATH_SOON	= "显示“深呼吸 - 即将施放”警报"
	DBM_FELMYST_OPTION_VAPOR		= "警报恶魔蒸汽的目标"

	DBM_FELMYST_EMOTE_BREATH		= "%s深深地吸了一口气。"

	DBM_FELMYST_WARN_GAS			= "毒气新星"
	DBM_FELMYST_WARN_GAS_SOON		= "毒气新星 - 即将施放"
	DBM_FELMYST_WARN_ENCAPS			= "压缩 -> >%s<"
	DBM_FELMYST_WARN_AIR			= "空中阶段"
	DBM_FELMYST_LAND_SOON			= "10秒后进入地面阶段"
	DBM_FELMYST_BREATH_SOON_FMT		= "深呼吸 #%d - 10秒后施放"
	DBM_FELMYST_BREATH_SOON5_FMT	= "深呼吸 #%d - 5秒后施放"
	DBM_FELMYST_BREATH_NOW_FMT		= "深呼吸 #%d"
	DBM_FELMYST_ENCAPS_WARN_SAY		= "我被压缩了！远离我！"
	DBM_FELMYST_WARN_VAPOR			= "恶魔蒸汽 -> >%s<"

	DBM_SBT["Enrage"]			= "激怒";
	DBM_SBT["Air Phase"]		= "空中阶段";
	DBM_SBT["Ground Phase"]		= "地面阶段";
	DBM_SBT["Next Gas Nova"]	= "下一次毒气新星";
	DBM_SBT["Gas Nova"]			= "毒气新星";
	DBM_SBT["Next Deep Breath"]	= "下一次深呼吸";
	DBM_SBT["Deep Breath"]		= "深呼吸";


-- Eredar Twins
	DBM_TWINS_NAME					= "艾瑞达双子"
	DBM_TWINS_DESCRIPTION			= "警报暗影之刃, 暗影新星, 混乱重击, 高热和燃烧"
	DBM_TWINS_OPTION_BLADES			= "警报暗影之刃"
	DBM_TWINS_OPTION_BUFF			= "警报高热"
	DBM_TWINS_OPTION_BLOW			= "警报混乱重击"
	DBM_TWINS_OPTION_BLOW_SOON		= "显示“混乱重击 - 即将施放”警报"
	DBM_TWINS_OPTION_CONFLAG		= "燃烧: 警报"
	DBM_TWINS_OPTION_CONFLAG2		= "燃烧: 密语目标"
	DBM_TWINS_OPTION_CONFLAG3		= "燃烧: 特殊警报"
	DBM_TWINS_OPTION_CONFLAG4		= "燃烧: 添加标记"
	DBM_TWINS_OPTION_CONFLAG5		= "燃烧: 声音警报"
	DBM_TWINS_OPTION_NOVA			= "暗影新星: 警报"
	DBM_TWINS_OPTION_NOVA2			= "暗影新星: 密语目标"
	DBM_TWINS_OPTION_NOVA3			= "暗影新星: 特殊警报"
	DBM_TWINS_OPTION_NOVA4			= "暗影新星: 添加标记"
	DBM_TWINS_OPTION_TOUCH1			= "对黑暗触摸技能显示特殊警报"
	DBM_TWINS_OPTION_TOUCH2			= "对烈焰触摸技能显示特殊警报"

	DBM_TWINS_MOB_WL				= "高阶术士奥蕾塞丝"
	DBM_TWINS_MOB_SOCR				= "萨洛拉斯女王"
	DBM_TWINS_EMOTE_CONFLAG			= "奥蕾塞丝向([^%s]+)施放燃烧。"
	DBM_TWINS_EMOTE_NOVA			= "萨洛拉丝向([^%s]+)施放暗影新星。"

	DBM_TWINS_WARN_BLADES			= "暗影之刃"
	DBM_TWINS_WARN_NOVA_ON			= "暗影新星 -> >%s<"
	DBM_TWINS_WARN_BUFF				= "高热"
	DBM_TWINS_WARN_CONFLAG_ON		= "燃烧 -> >%s<"
	DBM_TWINS_WARN_BLOW_SOON		= "混乱重击 - 即将施放"
	DBM_TWINS_WARN_BLOW				= "混乱重击"
	DBM_TWINS_WHISPER_CONFLAG		= "燃烧！"
	DBM_TWINS_WHISPER_NOVA			= "暗影新星！"
	
	DBM_TWINS_SPECWARN_SHADOW		= "黑暗触摸: %d"
	DBM_TWINS_SPECWARN_FIRE			= "烈焰触摸: %d"

	DBM_SBT["Shadow Blades"]			= "暗影之刃";
	DBM_SBT["Next Shadow Blades"]		= "下一次暗影之刃";
	DBM_SBT["Next Shadow Nova"]			= "下一次暗影新星";
	DBM_SBT["Shadow Nova"]				= "暗影新星";
	DBM_SBT["Confounding Blow"]			= "混乱重击";
	DBM_SBT["Next Confounding Blow"]	= "下一次混乱重击";


-- M'uru
	DBM_MURU_NAME					= "穆鲁"
	DBM_MURU_DESCRIPTION			= "警报黑暗, 黑暗魔, 黑洞, 虚空戒卫和暗誓精灵刷新"
	DBM_MURU_OPTION_VOID			= "警报虚空戒卫刷新"
	DBM_MURU_OPTION_VOID_SOON		= "显示“虚空戒卫 - 5秒后出现”警报"
	DBM_MURU_OPTION_HUM				= "警报暗誓精灵刷新"
	DBM_MURU_OPTION_HUM_SOON		= "显示“暗誓精灵 - 5秒后出现”警报"
	DBM_MURU_OPTION_DARKNESS		= "在第一阶段警报黑暗和黑暗魔"
	DBM_MURU_OPTION_DARKNESS_SOON	= "显示“黑暗/黑暗魔 - 5秒后施放”警报"
	DBM_MURU_OPTION_HOLE_WARN		= "警报黑洞"
	DBM_MURU_OPTION_HOLE_SOON_WARN	= "显示“黑洞 - 即将出现”警报"
	DBM_MURU_OPTION_WARN_FIEND		= "在第二阶段警报黑暗魔"

	DBM_MURU_ENTROPIUS				= "熵魔"

	DBM_MURU_DARKNESS_SOON			= "黑暗/黑暗魔 - 5秒后施放"
	DBM_MURU_DARKNESS_INC			= "黑暗/黑暗魔"
	DBM_MURU_WARN_VOID_SOON			= "虚空戒卫 - 5秒后出现"
	DBM_MURU_WARN_VOID_NOW			= "虚空戒卫出现"
	DBM_MURU_WARN_HUMANOIDS_SOON	= "暗誓精灵 - 5秒后出现"
	DBM_MURU_WARN_HUMANOIDS_NOW		= "暗誓精灵出现"
	DBM_MURU_WARN_FIEND				= "黑暗魔出现"
	DBM_MURU_WARN_BLACKHOLE			= "黑洞出现"
	DBM_MURU_WARN_BLACKHOLE_SOON	= "黑洞 - 即将出现"
	DBM_MURU_WARN_P2				= "第二阶段"

	DBM_SBT["Enrage"]				= "激怒";
	DBM_SBT["Humanoids"]			= "暗誓精灵";
	DBM_SBT["Void Sentinel"]		= "虚空戒卫";
	DBM_SBT["Next Darkness"]		= "下一次黑暗";
	DBM_SBT["Next Black Hole"]		= "下一次黑洞";


-- Kil'jaeden
	DBM_KIL_NAME					= "基尔加丹"
	DBM_KIL_DESCRIPTION				= "警报宝珠, 黑暗, 蓝龙之盾, 邪恶镜像, 火焰之花"

	DBM_KIL_OPTION_RANGE			= "显示距离框体"
	DBM_KIL_OPTION_SHIELD			= "警报蓝龙之盾"
	DBM_KIL_OPTION_ORB				= "警报宝珠"
	DBM_KIL_OPTION_FIRETARGET		= "警报火焰之花的目标"
	DBM_KIL_OPTION_FIRESAY			= "当你受到火焰之花效果时喊话"
	DBM_KIL_OPTION_FIREWHISP		= "对火焰之花的目标发送密语"
	DBM_KIL_OPTION_FIREICON			= "对火焰之花的目标添加标记"
	DBM_KIL_OPTION_SHOWFRAME		= "显示火焰之花的目标列表"
	DBM_KIL_OPTION_WARNREFL			= "警报邪恶镜像"
	DBM_KIL_OPTION_DARTS			= "警报烈焰之刺"
	DBM_KIL_OPTION_DRAGONORB		= "警报龙类宝珠"

	DBM_KIL_YELL_PULL				= "这个消耗品已经没用了，不管她了！现在我已经做到了连萨格拉斯都没有做到的事情！我要彻底毁灭这个世界，真正成为燃烧军团的主宰者！末日已经到来了！让这个世界就此支离破碎吧！"
	DBM_KIL_YELL_PHASE2_1			= "敌人就在你们中间！"
	DBM_KIL_YELL_PHASE2_2			= "你还能相信谁！"

	DBM_KIL_WARN_PHASE1				= "第二阶段"
	DBM_KIL_WARN_PHASE2				= "第三阶段"
	DBM_KIL_WARN_PHASE3				= "第四阶段 - 流星"
	DBM_KIL_WARN_PHASE4				= "第五阶段 - 激怒"
	DBM_KIL_WARN_SHIELD				= "蓝龙之盾"
	DBM_KIL_WARN_DARKNESS			= "黑暗"
	DBM_KIL_WARN_DARKNESS_SOON		= "黑暗 - 即将施放"
	DBM_KIL_WARN_ORB				= "宝珠出现"
	DBM_KIL_WARN_ORBS				= "宝珠出现"
	--DBM_KIL_WARN_FIRE				= "Fire Bloom incoming"
	DBM_KIL_WARN_FIRE_ON			= "火焰之花 -> >%s<"
	DBM_KIL_WARN_DARKNESS_NOW		= "千魂之暗"
	DBM_KIL_WARN_REFLECTIONS		= "邪恶镜像"
	DBM_KIL_WARN_FIRE_SAY			= "我中了火焰之花！"
	DBM_KIL_WARN_FIRE_WHISPER		= "火焰之花！"
	DBM_KIL_WARN_DARTS_SOON			= "烈焰之刺 - 5秒后施放"
	DBM_KIL_WARN_DARTS				= "烈焰之刺"
	DBM_KIL_WARN_DRAGORB_SOON		= "龙类宝珠 - 5秒后出现"
	DBM_KIL_WARN_DRAGORB_NOW		= "龙类宝珠出现"

	DBM_KIL_FRAME_TITLE				= "火焰之花"
	DBM_KIL_MENU_LOCK				= DBM_KAL_MENU_LOCK
	DBM_KIL_FRAME_COLORS			= DBM_KAL_FRAME_COLORS
	DBM_KIL_FRAME_UPWARDS			= "火焰之花目列表体向上延伸"
	DBM_KIL_FRAME_UPWARDS2			= DBM_KAL_FRAME_UPWARDS2
	DBM_KIL_FRAME_HIDE				= DBM_KAL_FRAME_HIDE

	DBM_SBT["Fire Bloom CD"]		= "火焰之花冷却";
	DBM_SBT["Flame Darts"]			= "烈焰之刺";
	DBM_SBT["Dragon Orb"]			= "龙类宝珠";


end