if (GetLocale() == "zhTW") then

--   Deadly Boss Mods - Chinese localization   --
--    by kc10577 Nightkiller@日落沼澤          --
--                  05-Aug-08                  --

DBM_SW_TAB				= "SunwellTab"
DBM_SUNWELL				= "太陽之井高地"

-- Kalecgos
DBM_KAL_NAME				= "卡雷苟斯"
DBM_KAL_DESCRIPTION 			= "提供冰霜吐息, 野性魔法, 和無盡痛苦詛咒提示和計時器."

DBM_KAL_KILL_NAME			= "『墮落者』塞斯諾瓦"
DBM_KAL_DEMON_SHORT			= "塞斯諾瓦"

DBM_KAL_OPTION_BREATH			= "提示冰霜吐息"
DBM_KAL_OPTION_PREBREATH		= "顯示\"即將發動冰霜吐息\"警告"
DBM_KAL_OPTION_WM_WARN			= "提示野性魔法"
DBM_KAL_OPTION_WM_WHISPER		= "發送密語給中了野性魔法的人"
DBM_KAL_OPTION_COA_WARN			= "提示無盡痛苦詛咒"
DBM_KAL_OPTION_COA_ICON			= "標記中了無盡痛苦詛咒的人"
DBM_KAL_OPTION_PORT_PREWARN		= "顯示\"即將發動傳送門\"警告"
DBM_KAL_OPTION_PORT_WARN		= "提示傳送門"
DBM_KAL_OPTION_WM_WARN2			= "顯示野性魔法類型"
DBM_KAL_OPTION_SHOWFRAME		= "顯示鬼靈國度框架"
DBM_KAL_FRAME_UPWARDS			= "鬼靈國度框架向上延伸"
DBM_KAL_FRAME_UPWARDS2			= "向上延伸"
DBM_KAL_FRAME_COLORS			= "使用職業顏色"
DBM_KAL_OPTION_RANGE			= "顯示距離框"
DBM_KAL_OPTION_STRIKE			= "提示腐蝕之擊"
DBM_KAL_OPTION_FRAME			= "顯示血量框架"

DBM_KAL_SPELLID_BREATH			= 44799
--not a localization table... -> DO NOT TRANSLATE! 不要翻譯這個
DBM_KAL_SPELLIDS_WM			= {
	[44978] = "Heal",	-- Healing done by spells and effects increased by 100%.
	[45001] = "Cast",	-- Casting time increased by 100%.
	[45002] = "Hit",	-- Chance to hit with melee and ranged attacks reduced by 50%.
	[45004] = "Crit",	-- Damage done by critical hits increased by 100%.
	[45006] = "Aggro",	-- Increases threat generated by 100%.
	[45010] = "Cost"	-- Spell and ability costs reduced by 50%.
}
DBM_KAL_SPELLID_COA1			= 45032
DBM_KAL_SPELLID_COA2			= 45034
DBM_KAL_SPELLID_PORT1			= 46021
DBM_KAL_SPELLID_BLAST			= 44866
DBM_KAL_SPELLID_BUFFET			= 45018
DBM_KAL_YELL_PULL			= "啊!!我不再是瑪里苟斯的奴隸了!所有挑戰我的人都要被消滅!"

DBM_KAL_WARN_BREATH			= "冰霜吐息"
DBM_KAL_WARN_BREATH_SOON		= "冰霜吐息 即將發動"
DBM_KAL_WHISPER_WM			= "野性魔法: %s"
DBM_KAL_WARN_COA			= "無盡痛苦詛咒: >%s<"
DBM_KAL_WARN_PORT			= "第 %s 個傳送門: >%s< (第%d隊)"
DBM_KAL_WARN_PORT_SOON			= "第 %s 個傳送門 即將發動"
DBM_KAL_WARN_STRIKE			= "腐蝕之擊: >%s<"

DBM_KAL_WARN_CASTTIME			= "+100%施法時間"
DBM_KAL_WARN_HIT			= "-50%命中機率"
DBM_KAL_WARN_CRIT			= "+100%爆擊傷害"
DBM_KAL_WARN_AGGRO			= "+100%仇恨值"
DBM_KAL_WARN_COST			= "-50%法術消耗"
DBM_KAL_WARN_HEAL			= "+100%治療"

DBM_KAL_FRAME_TITLE			= "鬼靈國度"
DBM_KAL_MENU_LOCK			= "鎖定框架"
DBM_KAL_FRAME_HIDE			= "隱藏框架"

DBM_KAL_HEALTHFRAME_TITLE		= "藍龍/惡魔 血量"

DBM_SBT["Arcane Buffet"]		= "秘法之擊";
DBM_SBT["Frost Breath"]			= "冰霜吐息";
DBM_SBT["Ported"]			= "已傳送";
DBM_SBT["Exhausted"]			= "鬼靈枯竭";
DBM_SBT["Kal"] = {
		 [1] = {"CoA: (.*)", "無盡痛苦詛咒: %1"},
		 [2] = {"Next Portal #(.*)", "下一次 傳送門 #%1"},
		 [3] = {"Portal #(.*)", "傳送門 #%1"},		
}

-- Brutallus 
DBM_BRUTALLUS_NAME			= "布魯托魯斯" 
DBM_BRUTALLUS_DESCRIPTION		= "提供燃燒和狂怒提示和計時器."

DBM_BRUTALLUS_YELL_PULL			= "啊，更多待宰的小羊們!"

DBM_BRUTALLUS_OPTION_BURN		= "提示燃燒"
DBM_BRUTALLUS_OPTION_BURN2		= "提示跳躍燃燒"
DBM_BRUTALLUS_OPTION_BAR_BURN2		= "跳躍燃燒: <target>"
DBM_BRUTALLUS_OPTION_METEOR		= "提示隕石斬"
DBM_BRUTALLUS_OPTION_STOMP		= "提示踐踏"
DBM_BRUTALLUS_OPTION_BURN3		= "標記中了燃燒的人"
DBM_BRUTALLUS_OPTION_BURN4		= "顯示特別警告當你中了燃燒"
DBM_BRUTALLUS_OPTION_DEL_BURN		= "顯示延遲了的燃燒計時器"
DBM_BRUTALLUS_OPTION_DEL_BURN2		= "顯示延遲了的燃燒提示"
DBM_BRUTALLUS_OPTION_PRESTOMP		= "顯示踐踏的5秒警告"

DBM_BRUTALLUS_WARN_BURN			= "燃燒: >%s<"
DBM_BRUTALLUS_WHISP_BURN		= "你中了燃燒!"
DBM_BRUTALLUS_WARN_STOMP		= "踐踏: >%s<"
DBM_BRUTALLUS_WARN_METEOR		= "隕石斬"
DBM_BRUTALLUS_WARN_DEL_BURN		= "15秒燃燒: >%s<"
DBM_BRUTALLUS_WARN_STOMP_SOON		= "5秒後 踐踏"

DBM_SBT["Enrage"]			= "狂怒";
DBM_SBT["Next Burn"]			= "下一次 燃燒";
DBM_SBT["Next Meteor"]			= "下一次 隕石斬";
DBM_SBT["Next Stomp"]			= "下一次 踐踏";
DBM_SBT["Brutallus"] = {
		 [1] = {"Burn: (.*)", "燃燒: %1"},
		 [2] = {"Jumped Burn: (.*)", "跳躍燃燒: %1"},
}


-- Felmyst
DBM_FELMYST_NAME			= "魔龍謎霧"
DBM_FELMYST_DESCRIPTION			= "提示毒氣新星, 深呼吸和惡魔煙霧"

DBM_FELMYST_OPTION_SPECGAS		= "為毒氣新星顯示特別警告"
DBM_FELMYST_OPTION_GASSOON		= "顯示\"即將發動毒氣新星\"警告 (不準確!)"
DBM_FELMYST_OPTION_BREATH_SOON		= "顯示\"即將發動深呼吸\"警告"
DBM_FELMYST_OPTION_VAPOR		= "提示惡魔煙霧的目標"

DBM_FELMYST_SPELL_ENCAPS		= "封印"

DBM_FELMYST_EMOTE_BREATH		= "%s深深地吸了一口氣"

DBM_FELMYST_WARN_GAS			= "毒氣新星"
DBM_FELMYST_WARN_GAS_SOON		= "毒氣新星 即將發動"
DBM_FELMYST_WARN_ENCAPS			= "封印: >%s<"
DBM_FELMYST_WARN_AIR			= "空中階段"
DBM_FELMYST_LAND_SOON			= "10秒後 地上階段"
DBM_FELMYST_BREATH_SOON_FMT		= "10秒後 第%d個深呼吸"
DBM_FELMYST_BREATH_SOON5_FMT		= "5秒後 第%d個深呼吸"
DBM_FELMYST_BREATH_NOW_FMT		= "第%d個深呼吸"
DBM_FELMYST_ENCAPS_WARN_SAY		= "封印在我身上!快跑開!"
DBM_FELMYST_WARN_VAPOR			= "惡魔煙霧: >%s<"

DBM_SBT["Next Gas Nova"]		= "下一次 毒氣新星";
DBM_SBT["Gas Nova"]			= "毒氣新星";
DBM_SBT["Ground Phase"]			= "地上階段";
DBM_SBT["Air Phase"]			= "空中階段";
DBM_SBT["Next Deep Breath"]		= "下一次深呼吸";

-- Eredar Twins
DBM_TWINS_NAME				= "埃雷達爾雙子"
DBM_TWINS_DESCRIPTION			= "提供暗影之刃, 暗影新星, 燃燒, 焦化和燃燒提示和計時器."
DBM_TWINS_OPTION_BLADES			= "提示暗影之刃"
DBM_TWINS_OPTION_BUFF			= "提示焦化"
DBM_TWINS_OPTION_BLOW			= "提示混亂痛擊"
DBM_TWINS_OPTION_BLOW_SOON		= "顯示\"即將發動混亂痛擊\"警告"
DBM_TWINS_OPTION_CONFLAG		= "燃燒: 提示"
DBM_TWINS_OPTION_CONFLAG2		= "燃燒: 密語提示"
DBM_TWINS_OPTION_CONFLAG3		= "燃燒: 特別警告"
DBM_TWINS_OPTION_CONFLAG4		= "燃燒: 標記"
DBM_TWINS_OPTION_CONFLAG5		= "燃燒: 聲音"
DBM_TWINS_OPTION_NOVA			= "暗影新星: 提示"
DBM_TWINS_OPTION_NOVA2			= "暗影新星: 密語提示"
DBM_TWINS_OPTION_NOVA3			= "暗影新星: 特別警告"
DBM_TWINS_OPTION_NOVA4			= "暗影新星: 標記"
DBM_TWINS_OPTION_TOUCH1			= "為黑暗碰觸顯示特別警告"
DBM_TWINS_OPTION_TOUCH2			= "為烈焰碰觸顯示特別警告"

DBM_TWINS_MOB_WL			= "大術士艾黎瑟絲"
DBM_TWINS_MOB_SOCR			= "莎珂蕾希女士"
DBM_TWINS_EMOTE_CONFLAG			= "艾黎瑟絲對(.+)施放燃燒"
DBM_TWINS_EMOTE_NOVA			= "莎珂蕾希對(.+)施放暗影新星"

DBM_TWINS_WARN_BLADES			= "暗影之刃"
DBM_TWINS_WARN_NOVA_ON			= "暗影新星: >%s<"
DBM_TWINS_WARN_BUFF			= "焦化"
DBM_TWINS_WARN_CONFLAG_ON		= "燃燒: >%s<"
DBM_TWINS_WARN_BLOW_SOON		= "混亂痛擊 即將發動"
DBM_TWINS_WARN_BLOW			= "混亂痛擊"
DBM_TWINS_WHISPER_CONFLAG		= "你中了燃燒!"
DBM_TWINS_WHISPER_NOVA			= "你中了暗影新星!"

DBM_TWINS_SPECWARN_SHADOW		= "黑暗碰觸: %d"
DBM_TWINS_SPECWARN_FIRE			= "烈焰碰觸: %d"

DBM_SBT["Enrage"]			= "狂怒";
DBM_SBT["Shadow Blades"]		= "暗影之刃";
DBM_SBT["Next Shadow Blades"]		= "下一次 暗影之刃";
DBM_SBT["Next Shadow Nova"]		= "下一次 暗影新星";
DBM_SBT["Shadow Nova"]			= "暗影新星";
DBM_SBT["Confounding Blow"]		= "混亂痛擊";
DBM_SBT["Next Confounding Blow"]	= "下一次混亂痛擊";

-- M'uru
DBM_MURU_NAME				= "莫魯"
DBM_MURU_DESCRIPTION			= "提示黑暗, 惡魔, 黑洞, 虛無哨兵和人型生物的出現."
DBM_MURU_OPTION_VOID			= "提示虛無哨兵"
DBM_MURU_OPTION_VOID_SOON		= "為虛無哨兵顯示5秒警告"
DBM_MURU_OPTION_HUM			= "提示人型生物"
DBM_MURU_OPTION_HUM_SOON		= "為人型生物顯示5秒警告"
DBM_MURU_OPTION_DARKNESS		= "提示第一階段的黑暗和惡魔"
DBM_MURU_OPTION_DARKNESS_SOON		= "顯示\"即將發動黑暗/惡魔\"警告"
DBM_MURU_OPTION_HOLE_WARN		= "提示黑洞"
DBM_MURU_OPTION_HOLE_SOON_WARN		= "顯示\"即將發動黑洞\"警告"
DBM_MURU_OPTION_WARN_FIEND		= "提示第二階段的惡魔"

DBM_MURU_ENTROPIUS			= "安卓普斯" --未確定

DBM_MURU_DARKNESS_SOON			= "5秒後 黑暗和惡魔"
DBM_MURU_DARKNESS_INC			= "黑暗和惡魔"
DBM_MURU_WARN_VOID_SOON			= "5秒後 虛無哨兵"
DBM_MURU_WARN_VOID_NOW			= "虛無哨兵 出現了"
DBM_MURU_WARN_HUMANOIDS_SOON		= "5秒後 人型生物"
DBM_MURU_WARN_HUMANOIDS_NOW		= "人型生物 出現了"
DBM_MURU_WARN_FIEND			= "黑暗惡魔 出現了"
DBM_MURU_WARN_BLACKHOLE			= "黑洞 出現了"
DBM_MURU_WARN_BLACKHOLE_SOON		= "即將發動 黑洞"
DBM_MURU_WARN_P2			= "第二階段"

DBM_SBT["Enrage"]			= "狂怒";
DBM_SBT["Humanoids"]			= "人型生物";
DBM_SBT["Void Sentinel"]		= "虛無哨兵";
DBM_SBT["Next Black Hole"]		= "下一次黑洞";
DBM_SBT["Muru"] = {
	{"Next Darkness", "下一次黑暗"},
}

-- Kil'jaeden
DBM_KIL_NAME				= "基爾加丹"
DBM_KIL_DESCRIPTION			= "提示盾之寶珠, 千魂之暗, 藍龍之盾, 邪惡倒影, 燃焰之矢, 龍類寶珠和火焰之花"

DBM_KIL_OPTION_RANGE			= "顯示距離框"
DBM_KIL_OPTION_SHIELD			= "提示藍龍之盾"
DBM_KIL_OPTION_ORB			= "提示盾之寶珠-群體暗影箭"
DBM_KIL_OPTION_FIRETARGET		= "提示火焰之花的目標"
DBM_KIL_OPTION_FIRESAY			= "當火焰之花施放在你身上時大叫"
DBM_KIL_OPTION_FIREWHISP		= "發送密語給火焰之花的目標"
DBM_KIL_OPTION_FIREICON			= "標記火焰之花目標"
DBM_KIL_OPTION_SHOWFRAME		= "顯示火焰之花目標列表"
DBM_KIL_OPTION_WARNREFL			= "提示邪惡倒影"
DBM_KIL_OPTION_DARTS			= "提示燃焰之矢"
DBM_KIL_OPTION_DRAGONORB		= "提示龍類寶珠"

DBM_KIL_YELL_PULL			= "該犧牲的都已經結束了，就任他們去吧!現在我將完成薩格拉斯都辦不到的事!我要搾乾這個悲慘的世界，並確保我成為燃燒軍團的真正主人!末日已經到來!讓這個世界開始毀滅吧!"
DBM_KIL_YELL_PHASE2_1			= "敵人就在你們之中!" -- this actually announces Sinister Reflections and not phase 2
DBM_KIL_YELL_PHASE2_2			= "你還能相信誰!"

DBM_KIL_WARN_PHASE1			= "第二階段"
DBM_KIL_WARN_PHASE2			= "第三階段"
DBM_KIL_WARN_PHASE3			= "第四階段 - 隕石"
DBM_KIL_WARN_PHASE4			= "第五階段 - 狂暴"
DBM_KIL_WARN_SHIELD			= "藍龍之盾"
DBM_KIL_WARN_DARKNESS			= "千魂之暗"
DBM_KIL_WARN_DARKNESS_SOON		= "即將發動 千魂之暗"
DBM_KIL_WARN_ORB			= "盾之寶珠-群體暗影箭 出現"
DBM_KIL_WARN_ORBS			= "多粒盾之寶珠-群體暗影箭 出現了"
--DBM_KIL_WARN_FIRE			= "火焰之花 即將出現"
DBM_KIL_WARN_FIRE_ON			= "火焰之花: >%s<"
DBM_KIL_WARN_DARKNESS_NOW		= "千魂之暗"
DBM_KIL_WARN_REFLECTIONS		= "邪惡倒影"
DBM_KIL_WARN_FIRE_SAY			= "火焰之花在我身上!"
DBM_KIL_WARN_FIRE_WHISPER		= "火焰之花在你身上!"
DBM_KIL_WARN_DARTS_SOON			= "5秒後 燃焰之矢"
DBM_KIL_WARN_DARTS			= "燃焰之矢"
DBM_KIL_WARN_DRAGORB_SOON		= "5秒後 藍龍寶珠"
DBM_KIL_WARN_DRAGORB_NOW		= "龍類寶珠 出現了"

DBM_KIL_FRAME_TITLE			= "火焰之花"
DBM_KIL_MENU_LOCK			= DBM_KAL_MENU_LOCK
DBM_KIL_FRAME_COLORS			= DBM_KAL_FRAME_COLORS
DBM_KIL_FRAME_UPWARDS			= "將火焰之花目標列表向上延伸"
DBM_KIL_FRAME_UPWARDS2			= DBM_KAL_FRAME_UPWARDS2
DBM_KIL_FRAME_HIDE			= DBM_KAL_FRAME_HIDE

DBM_SBT["Fire Bloom CD"]		= "火焰之花冷卻";
DBM_SBT["Flame Darts"]			= "燃焰之矢";
DBM_SBT["Darkness"]			= "千魂之暗";
DBM_SBT["Dragon Orb"]			= "龍類寶珠";
DBM_SBT["Kil"] = {
	{"Next Darkness", "下一次 千魂之暗"},
}

end