if GetLocale() ~= "ptBR" then return end
if not DBM_COMMON_L then DBM_COMMON_L = {} end

local CL = DBM_COMMON_L

--General
CL.NONE							= "Nenhum"
CL.RANDOM						= "Aleatório"
CL.UNKNOWN						= "Desconhecido"--UNKNOWN which is "Unknown" (does u vs U matter?)
CL.NEXT							= "Próximo %s"
CL.COOLDOWN						= "%s CD"
CL.INCOMING						= "%s a caminho"
CL.INTERMISSION					= "Intervalo"--No blizz global for this, and will probably be used in most end tier fights with intermission phases
CL.NO_DEBUFF					= "Não %s"--For use in places like info frame where you put "Not Spellname"
CL.ALLY							= "Aliado"--Such as "Move to Ally"
CL.ALLIES						= "Aliados"--Such as "Move to Allies"
CL.TANK							= "Tanque"--Such as "Move to Tank"
CL.CLEAR						= "Limpar"
CL.SAFE							= "Seguro"
CL.NOTSAFE						= "Não seguro"
CL.SEASONAL						= "Sazonal"--Used for option headers to label options that apply to seasonal mechanics (Such as season of mastery on classic era)
CL.FULLENERGY					= "Energia cheia"

--Movements/Places
CL.UP							= "Cima"
CL.DOWN							= "Baixo"
CL.LEFT							= "Esquerda"
CL.RIGHT						= "Direita"
CL.CENTER						= "Meio"
CL.BOTH							= "Ambos"
CL.BEHIND						= "Atrás"
CL.BACK							= "De trás"--Back as in back of the room, not back as in body part
CL.SIDE							= "Lado"--Side as in move to the side
CL.TOP							= "Topo"
CL.BOTTOM						= "Fundo"
CL.MIDDLE						= "Meio"
CL.FRONT						= "A frente"
CL.EAST							= "Leste"
CL.WEST							= "Oeste"
CL.NORTH         				= "Norte"
CL.SOUTH          				= "Sul"
CL.NORTHEAST      				= "Nordeste"
CL.SOUTHEAST      				= "Sudeste"
CL.SOUTHWEST      				= "Sudoeste"
CL.NORTHWEST      				= "Noroeste"
CL.INSIDE 						= "Dentro"
CL.OUTSIDE 						= "Fora"
CL.SHIELD						= "Escudo"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.PILLAR						= "Pilar"
CL.SHELTER						= "Abrigar"
CL.EDGE							= "Borda da sala"
CL.FAR_AWAY						= "Longe"
CL.PIT							= "Buraco"--Pit, as in hole in ground
CL.TOTEM						= "Totem"
CL.TOTEMS						= "Totens"
CL.HORIZONTAL					= "Horizontal"
CL.VERTICAL						= "Vertical"
--Mechanics
CL.BOMB							= "Bomba"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.BOMBS						= "Bombas"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.ORB							= "Orbe"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.ORBS							= "Orbes"--Doesn't have a direct auto localize so has to be manually localized, unlike non plural version
CL.RING							= "Anel"
CL.RINGS						= "Anéis "
CL.CHEST						= "Cofre"--As in Treasure 'Chest'. Not Chest as in body part.
CL.ADD							= "Add"--A fight Add as in "boss spawned extra adds"
CL.ADDS							= "Adds"
CL.ADDCOUNT						= "Add %s"
CL.BIG_ADD						= "Add grande"
CL.BIG_ADDS						= "Adds grandes"
CL.BOSS							= "Chefe"
CL.ENEMIES						= "Inimigos"
CL.BREAK_LOS         			= "Quebrar campo de visão"
CL.RESTORE_LOS       			= "Manter campo de visão"
CL.BOSSTOGETHER      			= "Chefes juntos"
CL.BOSSAPART         			= "Chefes separados"
CL.MINDCONTROL       			= "Controle mental"
CL.TANKCOMBO         			= "Combo de tanque"
CL.AOEDAMAGE         			= "Dano em área"
CL.AVOID						= "Evitar"
CL.GROUPSOAK         			= "Absorção"
CL.GROUPSOAKS        			= "Absorções"
CL.HEALABSORB        			= "Absorção de cura"
CL.HEALABSORBS       			= "Absorções de cura"
CL.DODGES            			= "Esquivas"
CL.POOL              			= "Poça"
CL.POOLS             			= "Poças"
CL.DEBUFFS           			= "Penalidade"
CL.DISPELS           			= "Dissipações"
CL.PUSHBACK          			= "Repulsão"
CL.FRONTAL           			= "Frontal"
CL.LASER            			= "Laser"
CL.LASERS            			= "Lasers"
CL.RIFT							= "Fenda"--Often has auto localized alternatives, but still translated for BW aura matching when needed
CL.RIFTS						= "Fendas"--Often has auto localized alternatives, but still translated for BW aura matching when needed
CL.TRAPS						= "Armadilhas"--Doesn't have a direct auto localize so has to be manually localized, unlike non plural version
CL.ROOTS						= "Enraizamento"
CL.MARK							= "Marca"--As in short text for all the encounter mechanics that start or end in "Mark"
CL.MARKS						= "Marcas"--Plural of above
CL.CURSE						= "Maldição"
CL.CURSES						= "Maldições"
CL.SWIRLS						= "Redemoinhos"--Plural of Swirl
CL.CHARGES						= "Cargas"--Context, this is plural of boss "charging to players" and NOT bomb charges
CL.CIRCLES						= "Círculos"--As in circles on ground that players need to move out of or need to drop off
-- Colors
CL.BLACK 						= "Preto"
CL.BLUE 						= "Azul"
CL.GREEN 						= "Verde"
CL.RED 							= "Vermelho"
CL.BRONZE 						= "Bronze"
