if GetLocale() ~= "frFR" then return end
if not DBM_COMMON_L then DBM_COMMON_L = {} end

local CL = DBM_COMMON_L

--General
CL.ALLIES				= "Alliés"--Such as "Move to Allies"
CL.ALLY					= "Allié"--Such as "Move to Ally"
CL.ALPHABETICAL			= "Alphabétique"
CL.CLEAR				= "Dégager"
CL.COOLDOWN				= "CD %s"
CL.DURATION				= "Durée"
CL.FULLENERGY			= "Energie pleine"
CL.INCOMING				= "%s arrive"
CL.INTERMISSION			= "Intervalle"--No blizz global for this, and will probably be used in most end tier fights with intermission phases
CL.NEXT					= "Prochain %s"
CL.NONE					= "Aucun"
CL.NO_DEBUFF			= "Pas %s"--For use in places like info frame where you put "Not Spellname"
CL.NOTSAFE				= "Pas sûr"
CL.RANDOM				= "Aléatoire"
CL.SAFE					= "Sûr"
CL.SEASONAL				= "Saisonnier"--Used for option headers to label options that apply to seasonal mechanics (Such as season of mastery on classic era)
CL.SORTING				= "Tri"
CL.TANK					= "Tank"--Such as "Move to Tank"
CL.UNKNOWN				= "Inconnu"--UNKNOWN which is "Unknown" (does u vs U matter?)

--Movements/Places
CL.BACK					= "Arrière"--Back as in back of the room, not back as in body part
CL.BEHIND				= "Derrière"
CL.BOTH					= "Les deux"
CL.BOTTOM				= "Bas"
CL.CENTER				= "Centre"
CL.DOWN					= "Bas"
CL.EAST					= "Est"
CL.EDGE					= "Bord de la pièce"
CL.FAR_AWAY				= "Très loin"
CL.FRONT				= "Avant"
CL.HORIZONTAL			= "Horizontal"
CL.INSIDE				= "Dedans"
CL.LEFT					= "Gauche"
CL.MIDDLE				= "Milieu"
CL.NORTH				= "Nord"
CL.NORTHEAST			= "Nord-est"
CL.NORTHWEST			= "Nord-ouest"
CL.OUTSIDE				= "Dehors"
CL.PILLAR				= "Pilier"
CL.PIT					= "Fosse"--Pit, as in hole in ground
CL.RIGHT				= "Droite"
CL.SHELTER				= "Abris"
CL.SHIELD				= "Bouclier"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.SIDE					= "Coté"--Side as in move to the side
CL.SOUTH				= "Sud"
CL.SOUTHEAST			= "Sud-est"
CL.SOUTHWEST			= "Sud-ouest"
CL.TOP					= "Haut"
CL.TOTEM				= "Totem"
CL.TOTEMS				= "Totems"
CL.UP					= "Haut"
CL.VERTICAL				= "Vertical"
CL.WEST					= "Ouest"

--Mechanics
CL.ADD					= "Add"--A fight Add as in "boss spawned extra adds"
CL.ADDCOUNT				= "Add %s"
CL.ADDS					= "Adds"
CL.AOEDAMAGE			= "Dégâts de zone"
CL.AVOID				= "Éviter"
CL.BALLS				= "Boules"
CL.BIG_ADD				= "Gros add"
CL.BIG_ADDS				= "Gros adds"
CL.BOMB					= "Bombe"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.BOMBS				= "Bombes"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.BOSS					= "Boss"
CL.BOSSAPART			= "Bosses séparés"
CL.BOSSTOGETHER			= "Bosses réunis"
CL.BREAK_LOS			= "Rompre LOS"
CL.CHEST				= "Coffre"--As in Treasure 'Chest'. Not Chest as in body part.
CL.CHARGES				= "Charges"--Context, this is plural of boss "charging to players" and NOT bomb charges
CL.CIRCLES				= "Cercles"--As in circles on ground that players need to move out of or need to drop off
CL.CURSE				= "Malédiction"
CL.CURSES				= "Malédictions"
CL.DEBUFF				= "Affaiblissement"
CL.DEBUFFS				= "Affaiblissements"
CL.DISPELS				= "Dissipations"
CL.DODGES				= "Esquives"
CL.ENEMIES				= "Ennemis"
CL.FRONTAL				= "Devant"
CL.GROUPSOAK			= "Absorption"
CL.GROUPSOAKS			= "Absorptions"
CL.HEALABSORB			= "Absorption de soins"
CL.HEALABSORBS			= "Absorptions de soins"
CL.INTERRUPT			= "Interruption"
CL.INTERRUPTS			= "Interruptions"
CL.KNOCKUP				= "Projeter dans les airs"
CL.LASER				= "Laser"
CL.LASERS				= "Lasers"
CL.LINE					= "Ligne"
CL.LINES				= "Lignes"
CL.MARK					= "Marque"--As in short text for all the encounter mechanics that start or end in "Mark"
CL.MARKS				= "Marques"--Plural of above
CL.MINDCONTROL			= "Contrôle mental"
CL.ORB					= "Orbe"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.ORBS					= "Orbes"--Doesn't have a direct auto localize so has to be manually localized, unlike non plural version
CL.POOL					= "Flaque"
CL.POOLS				= "Flaques"
CL.PUSHBACK				= "Repousser continu"
CL.RESTORE_LOS			= "Maintenir LOS"
CL.RIFT					= "Faille"--Often has auto localized alternatives, but still translated for BW aura matching when needed
CL.RIFTS				= "Failles"--Often has auto localized alternatives, but still translated for BW aura matching when needed
CL.ROOTS				= "Enracinement"
CL.RUNAWAY				= "Fuis"
CL.SPREAD				= "Disperse-toi"
CL.SPREADDEBUFF			= "Propage l'affaiblissement"
CL.SPREADDEBUFFS		= "Propage les affaiblissements"
CL.SPREADS				= "Se dispersent"
CL.SWIRLS				= "Tourbillon"--Plural of Swirl
CL.TRAPS				= "Pièges"--Doesn't have a direct auto localize so has to be manually localized, unlike non plural version

-- Colors
CL.BLACK			    = "Noir"
CL.BLUE			        = "Bleu"
CL.BRONZE		        = "Bronze"
CL.GREEN		        = "Vert"
CL.RED			        = "Rouge"

-- Conjunctions, used to join words, e.g., "Spell1 *and* Spell2 on you!"
CL.AND = "et"
CL.OR = "ou"
