if GetLocale() ~= "deDE" then return end
if not DBM_COMMON_L then DBM_COMMON_L = {} end

local CL = DBM_COMMON_L

--General
CL.ALPHABETICAL              = "Alphabetisch"
CL.DURATION                  = "Dauer"
CL.SORTING                   = "Sortierung"
CL.NONE                      = "Keine"
CL.RANDOM                    = "Zufällig"
CL.UNKNOWN                   = "Unbekannt"
CL.NEXT                      = "Nächste %s"
CL.COOLDOWN                  = "%s CD"
CL.INCOMING                  = "%s kommt"
CL.INTERMISSION              = "Übergang"
CL.NO_DEBUFF                 = "Kein %s"
CL.ALLY                      = "Verbündeten"
CL.ALLIES                    = "Verbündeten"
CL.TANK                      = "Tank"
CL.CLEAR                     = "Zurücksetzen"
CL.SAFE                      = "Sicher"
CL.NOTSAFE                   = "Nicht sicher"
CL.SEASONAL                  = "Saisonal"
CL.FULLENERGY                = "Volle Energie"

-- Movements/Places
CL.UP                        = "Oben"
CL.DOWN                      = "Unten"
CL.LEFT                      = "Links"
CL.RIGHT                     = "Rechts"
CL.CENTER                    = "Mitte"
CL.BOTH                      = "Beide"
CL.BEHIND                    = "Hinten"
CL.BACK                      = "Hinten"
CL.SIDE                      = "Seite"
CL.TOP                       = "Oben"
CL.BOTTOM                    = "Unten"
CL.MIDDLE                    = "Mitte"
CL.FRONT                     = "Vorne"
CL.EAST                      = "Osten"
CL.WEST                      = "Westen"
CL.NORTH                     = "Norden"
CL.SOUTH                     = "Süden"
CL.NORTHEAST                 = "Nord-Osten"
CL.SOUTHEAST                 = "Süd-Osten"
CL.SOUTHWEST                 = "Süd-Westen"
CL.NORTHWEST                 = "Nord-Westen"

CL.SHIELD                    = "Schutzschild"
CL.PILLAR                    = "Säule"
CL.SHELTER                   = "Deckung"
CL.EDGE                      = "Rand des Raums"
CL.FAR_AWAY                  = "Weit weg"
CL.PIT                       = "Grube"
CL.TOTEM                     = "Totem"
CL.TOTEMS                    = "Totems"
CL.HORIZONTAL                = "Horizontal"
CL.VERTICAL                  = "Vertikal"

-- Mechanics
CL.BOMB                       = "Bombe"
CL.BOMBS                      = "Bomben"
CL.ORB                        = "Kugel"
CL.ORBS                       = "Kugeln"
CL.RING                       = "Ring"
CL.RINGS                      = "Ringe"
CL.CHEST                      = "Kiste"
CL.ADD                        = "Add"
CL.ADDS                       = "Adds"
CL.ADDCOUNT                   = "Add %s"
CL.BIG_ADD                    = "Großes Add"
CL.BOSS                       = "Boss"
CL.ENEMIES                    = "Gegner"
CL.BREAK_LOS                  = "Meide Sichtlinie"
CL.RESTORE_LOS                = "Sichtlinie wiederherstellen"
CL.BOSSTOGETHER               = "Bosses Zusammen"
CL.BOSSAPART                  = "Bosses Getrennt"
CL.MINDCONTROL                = "Gedankenkontrolle"
CL.TANKCOMBO                  = "Tank-Kombo"
CL.AOEDAMAGE                  = "AOE-Schaden"
CL.GROUPSOAK                  = "Soak"
CL.GROUPSOAKS                 = "Soaks"
CL.HEALABSORB                 = "Heilungsaufnahme"
CL.HEALABSORBS                = "Heilungsaufnahmen"
CL.DODGES                     = "Ausweichen"
CL.POOL                       = "Pool"
CL.POOLS                      = "Pools"
CL.DEBUFFS                    = "Penalitäten"
CL.DISPELS                    = "Bannungen"
CL.PUSHBACK                   = "Rückstoß"
CL.FRONTAL                    = "Frontal"
CL.LASER                      = "Laser"
CL.LASERS                     = "Laser"
CL.RIFT                       = "Riss"
CL.RIFTS                      = "Risse"
CL.TRAPS                      = "Fallen"
CL.ROOTS                      = "Wurzeln"
CL.MARK                       = "Markierung"
CL.MARKS                      = "Markierungen"
CL.CURSE                      = "Fluch"
CL.CURSES                     = "Flüche"
CL.SWIRLS                     = "Wirbel"
CL.CHARGES                    = "Aufladungen"
CL.CIRCLES                    = "Kreise"
CL.KNOCKUP                    = "Hochschleudern"
CL.NEGATIVE                   = "Negativ"
CL.POSITIVE                   = "Positiv"

-- Colors
CL.BLACK	= "Schwarz"
CL.BLUE		= "Blau"
CL.GREEN	= "Grün"
CL.RED		= "Rot"
CL.BRONZE	= "Bronze"


-- Conjunctions, used to join words, e.g., "Spell1 *and* Spell2 on you!"
CL.AND		= "und"
CL.OR		= "oder"
