if GetLocale() ~= "itIT" then return end
if not DBM_COMMON_L then DBM_COMMON_L = {} end

local CL = DBM_COMMON_L

--General
CL.ALLIES			= "Alleati"--Such as "Move to Allies"
CL.ALLY				= "Alleato"--Such as "Move to Ally"
CL.ALPHABETICAL		= "Alfabetico"
CL.CLEAR			= "Azzera"
CL.COOLDOWN			= "%s CD"
CL.DURATION			= "Durata"
CL.FULLENERGY		= "Energia Piena"
CL.INCOMING			= "%s in Arrivo"
CL.INTERMISSION		= "Interfase"--No blizz global for this, and will probably be used in most end tier fights with intermission phases
CL.NEXT				= "Avanti %s"
CL.NONE				= "Nessuno"
CL.NO_DEBUFF		= "No %s"--For use in places like info frame where you put "Not Spellname"
CL.NOTSAFE			= "Non Sicuro"
CL.RANDOM			= "Casuale"
CL.SAFE				= "Sicuro"
CL.SEASONAL			= "Stagionale"--Used for option headers to label options that apply to seasonal mechanics (Such as season of mastery on classic era)
CL.SORTING			= "Ordinamento"
CL.TANK				= "Tank"--Such as "Move to Tank"
CL.UNKNOWN			= "Sconosciuto"--UNKNOWN which is "Unknown" (does u vs U matter?)

--Movements/Places
CL.BACK				= "Indietro"--Back as in back of the room, not back as in body part
CL.BEHIND			= "Dietro"
CL.BOTH				= "Entrambi"
CL.BOTTOM			= "Fondo"
CL.CENTER			= "Centro"
CL.DOWN				= "Giù"
CL.EAST				= "Est"
CL.EDGE				= "Bordo Stanza"
CL.FAR_AWAY			= "Lontano"
CL.FRONT			= "Fronte"
CL.HORIZONTAL		= "Orizzontale"
CL.INSIDE			= "Dentro"
CL.LEFT				= "Sinistra"
CL.MIDDLE			= "Mezzo"
CL.NORTH			= "Nord"
CL.NORTHEAST		= "Nord-Est"
CL.NORTHWEST		= "Nord-Ovest"
CL.OUTSIDE			= "Fuori"
CL.PILLAR			= "Pilastro"
CL.PIT				= "Fossa"--Pit, as in hole in ground
CL.RIGHT			= "Destra"
CL.SHIELD			= "Scudo"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.SHELTER			= "Riparo"
CL.SIDE				= "Lato"--Side as in move to the side
CL.SOUTH			= "Sud"
CL.SOUTHEAST		= "Sud-Est"
CL.SOUTHWEST		= "Sud-Ovest"
CL.TOP				= "Cima"
CL.TOTEM			= "Totem"
CL.TOTEMS			= "Totem"
CL.UP				= "Su"
CL.VERTICAL			= "Verticale"
CL.WEST				= "Ovest"

--Mechanics
CL.ADD				= "Add"--A fight Add as in "boss spawned extra adds"
CL.ADDCOUNT			= "Add %s"
CL.ADDS				= "Adds"
CL.AOEDAMAGE		= "Danno AOE"
CL.AVOID			= "Evitare"
CL.BALLS			= "Sfere"
CL.BIG_ADD			= "Add Grande"
CL.BIG_ADDS			= "Adds Grandi"
CL.BOMB				= "Bomba"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.BOMBS			= "Bombe"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.BOSS				= "Boss"
CL.BOSSAPART		= "Boss Separati"
CL.BOSSTOGETHER		= "Boss Insieme"
CL.BREAK_LOS		= "Interrompi LOS"
CL.CHARGES			= "Cariche"--Context, this is plural of boss "charging to players" and NOT bomb charges
CL.CHEST			= "Cassa"--As in Treasure 'Chest'. Not Chest as in body part.
CL.CIRCLES			= "Cerchi"--As in circles on ground that players need to move out of or need to drop off
CL.CURSE			= "Maledizione"
CL.CURSES			= "Maledizioni"
CL.DEBUFF			= "Debuff"
CL.DEBUFFS			= "Debuff"
CL.DISPELS			= "Dispel"
CL.DODGES			= "Schivate"
CL.ENEMIES			= "Nemici"
CL.FRONTAL			= "Frontale"
CL.GROUPSOAK		= "Assorbimento"
CL.GROUPSOAKS		= "Assorbimenti"
CL.HEALABSORB		= "Assorbimento di Cura"
CL.HEALABSORBS		= "Assorbimenti di Cura"
CL.INTERRUPT		= "Interruzione"
CL.INTERRUPTS		= "Interruzioni"
CL.KNOCK			= "Spinta"
CL.KNOCKUP			= "Proiettato in Aria"
CL.LASER			= "Laser"
CL.LASERS			= "Laser"
CL.LINE				= "Linea"
CL.LINES			= "Linee"
CL.MARK				= "Marchio"--As in short text for all the encounter mechanics that start or end in "Mark"
CL.MARKS			= "Marchi"--Plural of above
CL.MATHPUZZLE		= "Rompicapo matematico"
CL.MINDCONTROL		= "Controllo Mentale"
CL.NEGATIVE			= "Negativo"
CL.ORB				= "Sfera"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.ORBS				= "Sfere"--Doesn't have a direct auto localize so has to be manually localized, unlike non plural version
CL.PLAYERSWAPS		= "Scambi di giocatori"
CL.POOL				= "Pozza"
CL.POOLS			= "Pozze"
CL.POSITIVE			= "Positivo"
CL.PUSHBACK			= "Respinta"
CL.RESTORE_LOS		= "Ripristina/Mantieni LOS"
CL.RIFT				= "Varco"--Often has auto localized alternatives, but still translated for BW aura matching when needed
CL.RIFTS			= "Varchi"--Often has auto localized alternatives, but still translated for BW aura matching when needed
CL.RING				= "Anello"
CL.RINGS			= "Anelli"
CL.ROOTS			= "Radici"
CL.RUNAWAY			= "Scappa"
CL.SPREAD			= "Distanziati"
CL.SPREADDEBUFF		= "Distanzia il Debuff"
CL.SPREADDEBUFFS	= "Distanzia i Debuff"
CL.SPREADS			= "Si distanziano"
CL.SWIRLS			= "Vortici"--Plural of Swirl
CL.TANKBUSTER		= "Tank Buster"
CL.TANKCOMBO		= "Combo del Tank"
CL.TANKDEBUFF		= "Debuff del Tank"
CL.TRAPS			= "Trappole"--Doesn't have a direct auto localize so has to be manually localized, unlike non plural version
CL.WAVES			= "Onde"

-- Colors
CL.BLACK			= "Nero"
CL.BLUE			    = "Blu"
CL.BRONZE		    = "Bronzo"
CL.GREEN		    = "Verde"
CL.RED			    = "Rosso"

-- Conjunctions, used to join words, e.g., "Spell1 *and* Spell2 on you!"
CL.AND = "e"
CL.OR = "o"
