if GetLocale() ~= "ptBR" then return end
if not DBM_COMMON_L then DBM_COMMON_L = {} end

local CL = DBM_COMMON_L

--General
CL.ALLIES			= "Aliados"--Such as "Move to Allies"
CL.ALLY				= "Aliado"--Such as "Move to Ally"
CL.ALPHABETICAL		= "Alfabético"
CL.CLEAR			= "Limpar"
CL.COOLDOWN			= "%s CD"
CL.DURATION			= "Duração"
CL.FULLENERGY		= "Energia cheia"
CL.INCOMING			= "%s a caminho"
CL.INTERMISSION		= "Intervalo"--No blizz global for this, and will probably be used in most end tier fights with intermission phases
CL.NEXT				= "Próximo %s"
CL.NONE				= "Nenhum"
CL.NO_DEBUFF		= "Não %s"--For use in places like info frame where you put "Not Spellname"
CL.NOTSAFE			= "Não seguro"
CL.RANDOM			= "Aleatório"
CL.SAFE				= "Seguro"
CL.SEASONAL			= "Sazonal"--Used for option headers to label options that apply to seasonal mechanics (Such as season of mastery on classic era)
CL.SORTING			= "Ordenação"
CL.TANK				= "Tanque"--Such as "Move to Tank"
CL.UNKNOWN			= "Desconhecido"--UNKNOWN which is "Unknown" (does u vs U matter?)

--Movements/Places
CL.BACK				= "De trás"--Back as in back of the room, not back as in body part
CL.BEHIND			= "Atrás"
CL.BOTH				= "Ambos"
CL.BOTTOM			= "Fundo"
CL.CENTER			= "Meio"
CL.DOWN				= "Baixo"
CL.EAST				= "Leste"
CL.EDGE				= "Borda da sala"
CL.FAR_AWAY			= "Longe"
CL.FRONT			= "A frente"
CL.HORIZONTAL		= "Horizontal"
CL.INSIDE			= "Dentro"
CL.LEFT				= "Esquerda"
CL.MIDDLE			= "Meio"
CL.NORTH			= "Norte"
CL.NORTHEAST		= "Nordeste"
CL.NORTHWEST		= "Noroeste"
CL.OUTSIDE			= "Fora"
CL.PILLAR			= "Pilar"
CL.PIT				= "Buraco"--Pit, as in hole in ground
CL.RIGHT			= "Direita"
CL.SHELTER			= "Abrigar"
CL.SHIELD			= "Escudo"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.SIDE				= "Lado"--Side as in move to the side
CL.SOUTH			= "Sul"
CL.SOUTHEAST		= "Sudeste"
CL.SOUTHWEST		= "Sudoeste"
CL.TOP				= "Topo"
CL.TOTEM			= "Totem"
CL.TOTEMS			= "Totens"
CL.UP				= "Cima"
CL.VERTICAL			= "Vertical"
CL.WEST				= "Oeste"

--Mechanics
CL.ADD				= "Add"--A fight Add as in "boss spawned extra adds"
CL.ADDCOUNT			= "Add %s"
CL.ADDS				= "Adds"
CL.AOEDAMAGE		= "Dano em área"
CL.AVOID			= "Evitar"
CL.BALLS			= "Bolas"
CL.BIG_ADD			= "Add grande"
CL.BIG_ADDS			= "Adds grandes"
CL.BOMB				= "Bomba"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.BOMBS			= "Bombas"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.BOSS				= "Chefe"
CL.BOSSAPART		= "Chefes separados"
CL.BOSSTOGETHER		= "Chefes juntos"
CL.BREAK_LOS		= "Quebrar campo de visão"
CL.CHEST			= "Cofre"--As in Treasure 'Chest'. Not Chest as in body part.
CL.CHARGES			= "Cargas"--Context, this is plural of boss "charging to players" and NOT bomb charges
CL.CIRCLES			= "Círculos"--As in circles on ground that players need to move out of or need to drop off
CL.CURSE			= "Maldição"
CL.CURSES			= "Maldições"
CL.DEBUFF			= "Penalidade"
CL.DEBUFFS			= "Penalidades"
CL.DISPELS			= "Dissipações"
CL.DODGES			= "Esquivas"
CL.ENEMIES			= "Inimigos"
CL.FRONTAL			= "Frontal"
CL.GROUPSOAK		= "Absorção"
CL.GROUPSOAKS		= "Absorções"
CL.HEALABSORB		= "Absorção de cura"
CL.HEALABSORBS		= "Absorções de cura"
CL.INTERRUPT		= "Interrupção"
CL.INTERRUPTS		= "Interrupções"
CL.KNOCKUP			= "Derrubar"
CL.LASER			= "Laser"
CL.LASERS			= "Lasers"
CL.LINE				= "Linha"
CL.LINES			= "Linhas"
CL.MARK				= "Marca"--As in short text for all the encounter mechanics that start or end in "Mark"
CL.MARKS			= "Marcas"--Plural of above
CL.MINDCONTROL		= "Controle mental"
CL.ORB				= "Orbe"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.ORBS				= "Orbes"--Doesn't have a direct auto localize so has to be manually localized, unlike non plural version
CL.POOL				= "Poça"
CL.POOLS			= "Poças"
CL.PUSHBACK			= "Repulsão"
CL.RESTORE_LOS		= "Manter campo de visão"
CL.RIFT				= "Fenda"--Often has auto localized alternatives, but still translated for BW aura matching when needed
CL.RIFTS			= "Fendas"--Often has auto localized alternatives, but still translated for BW aura matching when needed
CL.ROOTS			= "Enraizamento"
CL.RUNAWAY			= "Fuja"
CL.SPREAD			= "Espalhe-se"
CL.SPREADDEBUFF		= "Espalhe a penalidade"
CL.SPREADDEBUFFS	= "Espalhe as penalidades"
CL.SPREADS			= "Se espalham"
CL.SWIRLS			= "Redemoinhos"--Plural of Swirl
CL.TRAPS			= "Armadilhas"--Doesn't have a direct auto localize so has to be manually localized, unlike non plural version

-- Colors
CL.BLACK			= "Preto"
CL.BLUE			    = "Azul"
CL.BRONZE		    = "Bronze"
CL.GREEN		    = "Verde"
CL.RED			    = "Vermelho"

-- Conjunctions, used to join words, e.g., "Spell1 *and* Spell2 on you!"
CL.AND = "e"
CL.OR = "ou"
