if GetLocale() ~= "esES" and GetLocale() ~= "esMX" then return end
if not DBM_COMMON_L then DBM_COMMON_L = {} end

local CL = DBM_COMMON_L

--General
CL.ALLIES			= "Aliados"--Such as "Move to Allies"
CL.ALLY				= "Aliado"--Such as "Move to Ally"
CL.ALPHABETICAL		= "Alfabético"
CL.CLEAR			= "Limpiar"
CL.COOLDOWN			= "%s TdR"
CL.DURATION			= "Duración"
CL.FULLENERGY		= "Energía al máximo"
CL.INCOMING			= "%s en breve"
CL.INTERMISSION		= "Intermedio"--No blizz global for this, and will probably be used in most end tier fights with intermission phases
CL.NEXT				= "Siguiente %s"
CL.NONE				= "Ninguno"
CL.NO_DEBUFF		= "Sin %s"--For use in places like info frame where you put "Not Spellname"
CL.NOTSAFE			= "Zona no segura"
CL.RANDOM			= "Aleatorio"
CL.SAFE				= "Zona segura"
CL.SEASONAL			= "Temporal"--Used for option headers to label options that apply to seasonal mechanics (Such as season of mastery on classic era)
CL.SORTING			= "Ordenación"
CL.TANK				= "Tanque"--Such as "Move to Tank"
CL.UNKNOWN			= "Desconocido"--UNKNOWN which is "Unknown" (does u vs U matter?)

--Movements/Places
CL.BACK					= "Atrás"--BACK
CL.BEHIND				= "Detrás"
CL.BOTH					= "Ambos"
CL.BOTTOM				= "Abajo"
CL.CENTER				= "Centro"
CL.DOWN					= "Abajo"
CL.EAST					= "Este"
CL.EDGE					= "Bordes de la sala"
CL.FAR_AWAY			    = "Lejos"
CL.FRONT				= "Delante"
CL.INSIDE				= "Adentro"
CL.LEFT					= "Izquierda"
CL.MIDDLE				= "Medio"
CL.NORTH				= "Norte"
CL.NORTHEAST			= "Noreste"
CL.NORTHWEST			= "Noroeste"
CL.OUTSIDE				= "Afuera"
CL.PILLAR				= "Pilar"
CL.PIT					= "Fosa"--Pit, as in hole in ground
CL.RIGHT				= "Derecha"
CL.SHELTER				= "Refugiarse"
CL.SHIELD				= "Escudo"
CL.SIDE					= "Lado"
CL.SOUTH				= "Sur"
CL.SOUTHEAST			= "Sureste"
CL.SOUTHWEST			= "Suroeste"
CL.TOP					= "Arriba"
CL.TOTEM				= "Tótem"
CL.TOTEMS				= "Tótems"
CL.UP					= "Arriba"
CL.VERTICAL				= "Vertical"
CL.WEST					= "Oeste"
CL.HORIZONTAL			= "Horizontal"

--Mechanics
CL.ADD					= "Esbirro"--A fight Add as in "boss spawned extra adds" - must check
CL.ADDCOUNT				= "Esbirro %s"
CL.ADDS					= "Esbirros"
CL.AOEDAMAGE			= "Daño AOE"
CL.AVOID				= "Evitar"
CL.BALLS				= "Bolas"
CL.BIG_ADD				= "Esbirro grande"
CL.BIG_ADDS				= "Esbirros grandes"
CL.BOMB					= "Bomba"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.BOMBS				= "Bombas"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.BOSS					= "Jefe"
CL.BOSSAPART			= "Jefes separados"
CL.BOSSTOGETHER		    = "Jefes juntos"
CL.BREAK_LOS			= "Romper la línea de mira"
CL.CHEST				= "Cofre"--As in Treasure 'Chest'. Not Chest as in body part.
CL.CHARGES				= "Cargas"--Context, this is plural of boss "charging to players" and NOT bomb charges
CL.CIRCLES				= "Círculos"--As in circles on ground that players need to move out of or need to drop off
CL.CURSE				= "Maldición"
CL.CURSES				= "Maldiciones"
CL.DEBUFF				= "Perjuicio"
CL.DEBUFFS				= "Perjuicios"
CL.DISPELS				= "Disipaciones"
CL.DODGES				= "Esquivas"
CL.ENEMIES				= "Enemigos"
CL.FRONTAL				= "Frontal"
CL.GROUPSOAK			= "Absorción"
CL.GROUPSOAKS			= "Absorciones"
CL.HEALABSORB			= "Absorción de sanación"
CL.HEALABSORBS			= "Absorciones de sanación"
CL.INTERRUPT			= "Interrupción"
CL.INTERRUPTS			= "Interrupciones"
CL.KNOCKUP				= "Agotar"
CL.LASER				= "Láser"
CL.LASERS				= "Láseres"
CL.LINE					= "Línea"
CL.LINES				= "Líneas"
CL.MARK					= "Marca"--As in short text for all the encounter mechanics that start or end in "Mark"
CL.MARKS				= "Marcas"--Plural of above
CL.MINDCONTROL			= "Control mental"
CL.NEGATIVE			    = "Negativo"
CL.ORB					= "Orbe"
CL.ORBS					= "Orbes"
CL.PLAYERSWAPS		    = "Intercambio de jugadores"
CL.POOL					= "Charco"
CL.POOLS				= "Charcos"
CL.POSITIVE			    = "Positivo"
CL.PUSHBACK				= "Empujón"
CL.RESTORE_LOS			= "Línea de mira"
CL.RIFT					= "Falla"--Often has auto localized alternatives, but still translated for BW aura matching when needed
CL.RIFTS				= "Fallas"--Often has auto localized alternatives, but still translated for BW aura matching when needed
CL.RING				    = "Anillo"
CL.RINGS			    = "Anillos"
CL.ROOTS				= "Raíces"
CL.RUNAWAY				= "Huye"
CL.SPREAD				= "Sepárate"
CL.SPREADDEBUFF			= "Extiende el perjuicio"
CL.SPREADDEBUFFS		= "Extiende los perjuicios"
CL.SPREADS				= "Se separan"
CL.SWIRLS				= "Remolinos"--Plural of Swirl
CL.TANKBUSTER		    = "Destructor de tanque"
CL.TANKCOMBO		    = "Combo de tanque"
CL.TANKDEBUFF		    = "Perjuicio del tanque"
CL.TRAPS				= "Trampas"

-- Colors
CL.BLACK    			= "Negro"
CL.BLUE    			    = "Azul"
CL.BRONZE  			    = "Bronce"
CL.GREEN   			    = "Verde"
CL.RED     			    = "Rojo"

-- Conjunctions, used to join words, e.g., "Spell1 *and* Spell2 on you!"
CL.AND = "y"
CL.OR = "o"
