if GetLocale() ~= "frFR" then return end
if not DBM_COMMON_L then DBM_COMMON_L = {} end

local CL = DBM_COMMON_L

--General
CL.NONE								= "Aucun"
CL.RANDOM							= "Aléatoire"
CL.UNKNOWN							= "Inconnu"--UNKNOWN which is "Unknown" (does u vs U matter?)
CL.NEXT								= "Prochain %s"
CL.COOLDOWN							= "CD %s"
CL.INCOMING							= "%s arrive"
CL.INTERMISSION						= "Intervalle"--No blizz global for this, and will probably be used in most end tier fights with intermission phases
CL.NO_DEBUFF						= "Pas %s"--For use in places like info frame where you put "Not Spellname"
CL.ALLY								= "Allié"--Such as "Move to Ally"
CL.ALLIES							= "Alliés"--Such as "Move to Allies"
CL.TANK								= "Tank"--Such as "Move to Tank"
CL.CLEAR							= "Dégager"
CL.SAFE								= "Sûr"
CL.NOTSAFE							= "Pas sûr"
CL.SEASONAL							= "Saisonnier"--Used for option headers to label options that apply to seasonal mechanics (Such as season of mastery on classic era)
CL.FULLENERGY						= "Energie pleine"
--Movements/Places
CL.UP								= "Haut"
CL.DOWN								= "Bas"
CL.LEFT								= "Gauche"
CL.RIGHT							= "Droite"
CL.CENTER							= "Centre"
CL.BOTH								= "Les deux"
CL.BEHIND							= "Derrière"
CL.BACK								= "Arrière"--Back as in back of the room, not back as in body part
CL.SIDE								= "Coté"--Side as in move to the side
CL.TOP								= "Haut"
CL.BOTTOM							= "Bas"
CL.MIDDLE							= "Milieu"
CL.FRONT							= "Avant"
CL.EAST								= "Est"
CL.WEST								= "Ouest"
CL.NORTH							= "Nord"
CL.SOUTH							= "Sud"
CL.NORTHEAST						= "Nord-est"
CL.SOUTHEAST						= "Sud-est"
CL.SOUTHWEST						= "Sud-ouest"
CL.NORTHWEST						= "Nord-ouest"
CL.INSIDE 							= "Dedans"
CL.OUTSIDE 							= "Dehors"
CL.SHIELD							= "Bouclier"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.PILLAR							= "Pilier"
CL.SHELTER							= "Abris"
CL.EDGE								= "Bord de la pièce"
CL.FAR_AWAY							= "Très loin"
CL.PIT								= "Fosse"--Pit, as in hole in ground
CL.TOTEM							= "Totem"
CL.TOTEMS							= "Totems"
CL.HORIZONTAL						= "Horizontal"
CL.VERTICAL							= "Vertical"
--Mechanics
CL.BOMB								= "Bombe"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.BOMBS							= "Bombes"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.ORB								= "Orbe"--Usually auto localized but kept around in case it needs to be used in a place that's not auto localized such as MoveTo or Use alert
CL.ORBS								= "Orbes"--Doesn't have a direct auto localize so has to be manually localized, unlike non plural version
CL.RING								= "Anneau"
CL.RINGS							= "Anneaux"
CL.CHEST							= "Coffre"--As in Treasure 'Chest'. Not Chest as in body part.
CL.ADD								= "Add"--A fight Add as in "boss spawned extra adds"
CL.ADDS								= "Adds"
CL.ADDCOUNT							= "Add %s"
CL.BIG_ADD							= "Gros add"
CL.BIG_ADDS							= "Gros adds"
CL.BOSS								= "Boss"
CL.ENEMIES							= "Ennemis"
CL.BREAK_LOS						= "Rompre LOS"
CL.RESTORE_LOS						= "Maintenir LOS"
CL.BOSSTOGETHER						= "Bosses réunis"
CL.BOSSAPART						= "Bosses séparés"
CL.MINDCONTROL						= "Contrôle mental"
CL.TANKCOMBO						= "Combo tank"
CL.AOEDAMAGE						= "Dégâts de zone"
CL.AVOID						    = "Éviter"
CL.GROUPSOAK						= "Absorption"
CL.GROUPSOAKS						= "Absorptions"
CL.HEALABSORB						= "Absorption de soins"
CL.HEALABSORBS						= "Absorptions de soins"
CL.DODGES							= "Esquives"
CL.POOL								= "Flaque"
CL.POOLS							= "Flaques"
CL.DEBUFFS							= "Affaiblissement"
CL.DISPELS							= "Dissipations"
CL.PUSHBACK							= "Repousser continu"
CL.FRONTAL							= "Devant"
CL.LASER							= "Laser"
CL.LASERS							= "Lasers"
CL.RIFT								= "Faille"--Often has auto localized alternatives, but still translated for BW aura matching when needed
CL.RIFTS							= "Failles"--Often has auto localized alternatives, but still translated for BW aura matching when needed
CL.TRAPS							= "Pièges"--Doesn't have a direct auto localize so has to be manually localized, unlike non plural version
CL.ROOTS							= "Enracinement"
CL.MARK								= "Marque"--As in short text for all the encounter mechanics that start or end in "Mark"
CL.MARKS							= "Marques"--Plural of above
CL.CURSE							= "Malédiction"
CL.CURSES							= "Malédictions"
CL.SWIRLS							= "Tourbillon"--Plural of Swirl
CL.CHARGES							= "Charges"--Context, this is plural of boss "charging to players" and NOT bomb charges
CL.CIRCLES							= "Cercles"--As in circles on ground that players need to move out of or need to drop off
-- Colors
CL.BLACK 							= "Noir"
CL.BLUE 							= "Bleu"
CL.GREEN 							= "Vert"
CL.RED 								= "Rouge"
CL.BRONZE 							= "Bronze"
