name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./workspace
      - name: Install and run Luacheck
        uses: BigWigsMods/luacheck@main
        with:
          args: "--no-color -q"
          config: https://raw.githubusercontent.com/DeadlyBossMods/DBM-Retail/refs/heads/master/.luacheckrc
          path: ./workspace

      - name: LuaLS check
        uses: DeadlyBossMods/LuaLS-config@main
        with:
          luals-check-dir: ${{ github.workspace }}/workspace

      - name: Send Status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
        if: ${{ failure() }}

  test-package:
    name: Test Package
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    needs:
      - test

    steps:
      - name: Checkout pull request
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Create test package
        uses: BigWigsMods/packager@master
        with:
          args: -d
          pandoc: false
      - name: Upload test packages
        uses: actions/upload-artifact@v4
        with:
          name: DBM-Retail-pr-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}
          path: .release/*.zip
          if-no-files-found: error
          retention-days: 14

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - test
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Create Package
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
