name: Full DBM-Offline results on push to master
run-name: DBM-Offline full

on:
  push:
    branches:
      - master

jobs:
  dbm-offline-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Run DBM-Offline
        continue-on-error: true
        uses: DeadlyBossMods/DBM-Offline@main
        with:
          diff-mode: false
          dbm-main-ref: ${{ github.event.after }}
          test-dbm-core-mods: true
          test-dbm-vanilla-mods: true
          test-dbm-dungeon-mods: true
          upload-repo-commit-message: ${{ format('Core{0} {1}', ':', join(github.event.commits.*.message, '\n')) }}
          upload-repo-branch: main
          upload-token: ${{ secrets.TEST_RESULT_UPLOAD_TOKEN }}
